name: Analyse

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Analyse using PHPStan
        timeout-minutes: 2
        run: ./vendor/bin/phpstan analyse --level 1 src tests --error-format=github
